name: Quality

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        include:
        - command: invoke black --check
        - command: invoke isort --check
        - command: invoke lint
        - command: invoke mypy
        os: ['ubuntu-18.04', 'windows-2019', 'macos-11']
        python-version: ['3.7', '3.8', '3.9']


    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Restore cache (Ubuntu)
      uses: actions/cache@v2
      if: startsWith(matrix.os, 'ubuntu-')
      with:
        path: ~/.cache/pip
        key: quality-pip-${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('requirements-test.txt', '.github/workflows/test.yml') }}
        restore-keys: quality-pip-${{ matrix.os }}-${{ matrix.python-version }}-

    - name: Restore cache (MacOS)
      uses: actions/cache@v2
      if: startsWith(matrix.os, 'macos-')
      with:
        path: ~/Library/Caches/pip
        key: quality-pip-${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('requirements-test.txt', '.github/workflows/test.yml') }}
        restore-keys: quality-pip-${{ matrix.os }}-${{ matrix.python-version }}-

    - name: Restore cache (Windows)
      uses: actions/cache@v2
      if: startsWith(matrix.os, 'windows-')
      with:
        path: ~\AppData\Local\pip\Cache
        key: quality-pip-${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('requirements-test.txt', '.github/workflows/test.yml') }}
        restore-keys: quality-pip-${{ matrix.os }}-${{ matrix.python-version }}-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel==0.35.1
        pip install Cython==0.29.28
        pip install setuptools==41.2.0
        pip install -r requirements-test.txt


    - name: Invoke Quality
      run: inv quality
