name: Quality

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        include:
        - command: invoke black --check
        - command: invoke isort --check
        - command: invoke lint
        - command: invoke mypy

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8

      uses: actions/setup-python@v2
      with:
        python-version: ['3.7', '3.8', '3.9']

    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: quality-pip-${{ hashFiles('requirements-test.txt', '.github/workflows/quality.yml') }}
        restore-keys: quality-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel==0.35.1
        pip install Cython==0.29.13
        pip install setuptools==41.2.0
        pip install -r requirements-test.txt


    - name: Invoke Quality
      run: inv quality
